### ISSUE TITLE
BOSH set up new environment on vSphere show "undefined method `effective_memory' for nil:NilClass"

### ISSUE THREAD

**Issue by liuyuewen91** [cloudfoundry-incubator/bosh-vsphere-cpi-release#142]
I use latest bosh cli to create -env on vsphere.

```
bosh -v
version 5.1.2-14b04789-2018-08-17T15:15:17Z

Succeeded

```
I use ubuntu 18.04 LTS.
I also installed the dependencies.
`sudo apt-get install -y build-essential zlibc zlib1g-dev ruby ruby-dev openssl libxslt-dev libxml2-dev libssl-dev libreadline6 libreadline6-dev libyaml-dev libsqlite3-dev sqlite3
`
Base on script blow.

```
# Create directory to keep state
$ mkdir bosh-1 && cd bosh-1

# Clone Director templates
$ git clone https://github.com/cloudfoundry/bosh-deployment

# Fill below variables (replace example values) and deploy the Director
$ bosh create-env bosh-deployment/bosh.yml \
    --state=state.json \
    --vars-store=creds.yml \
    -o bosh-deployment/vsphere/cpi.yml \
    -v director_name=bosh-1 \
    -v internal_cidr=10.0.0.0/24 \
    -v internal_gw=10.0.0.1 \
    -v internal_ip=10.0.0.6 \
    -v network_name="VM Network" \
    -v vcenter_dc=my-dc \
    -v vcenter_ds=datastore0 \
    -v vcenter_ip=192.168.0.10 \
    -v vcenter_user=root \
    -v vcenter_password=vmware \
    -v vcenter_templates=bosh-1-templates \
    -v vcenter_vms=bosh-1-vms \
    -v vcenter_disks=bosh-1-disks \
    -v vcenter_cluster=cluster1
```
And i get error msg: "undefined method `effective_memory' for nil:NilClass".
Can somebody please tell me, how to solve this error.

```
Deployment manifest: '/home/user/bosh/bosh-1/bosh-deployment/bosh.yml'
Deployment state: 'state.json'

Started validating
  Downloading release 'bosh'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh'... Finished (00:00:00)
  Downloading release 'bpm'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bpm'... Finished (00:00:00)
  Downloading release 'bosh-vsphere-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-vsphere-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:02)
Finished validating (00:00:04)

Started installing CPI
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Finished (00:00:00)
  Compiling package 'vsphere_cpi/e1a84e5bd82eb1abfe9088a2d547e2cecf6cf315'... Finished (00:00:00)
  Compiling package 'iso9660wrap/82cd03afdce1985db8c9d7dba5e5200bcc6b5aa8'... Finished (00:00:00)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'vsphere_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:01)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3586.24'... Failed (00:00:07)
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

creating stemcell (bosh-vsphere-esxi-ubuntu-trusty-go_agent 3586.24):
  CPI 'create_stemcell' method responded with error: CmdError{"type":"Unknown","message":"undefined method `effective_memory' for nil:NilClass","ok_to_retry":false}

Exit code 1
```

**Comment by liuyuewen91** [comment]
I was before created this issue at bosh-cli repo.
https://github.com/cloudfoundry/bosh-cli/issues/469#issuecomment-415881277

**Comment by EleanorRigby** [comment]
Which CPI version are you using?

**Comment by EleanorRigby** [comment]
Also the error seems to be coming from calculation of effective memory your
cluster has. Can you verify that you provided right cluster( i.e. cluster1
, does it exist in your vcenter)?

**Comment by liuyuewen91** [comment]
@EleanorRigby 
Thanks for your information. I think i use the latest vsphere-cpi.
I found in bosh-deployment/vsphere/cpi-cecondary.yml:
```
---
- type: replace
  path: /releases/-
  value:
    name: bosh-vsphere-cpi
    version: "50"
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-vsphere-cpi-release?v=50
    sha1: 27cad6e254f363ac06f947b4def3cbc7bfa269b9

- type: replace
  path: /instance_groups/name=bosh/properties/vcenter?
  value:
    address: unused
    user: unused
    password: unused
    datacenters:
    - name: unused
      vm_folder: unused
      template_folder: unused
      datastore_pattern: unused
      persistent_datastore_pattern: unused
      disk_path: unused
      clusters:
      - unused: {}

```

I will check the cluster of my vcenter.
thanks very much!
