### ISSUE TITLE
CPI does not pay attention to ESXI servers disconnected or in maintenance mode

### ISSUE THREAD

**Issue by jriguera** [cloudfoundry-incubator/bosh-vsphere-cpi-release#29]
We are running CPI version 38 (but I think this issue affects all versions) with Bosh director v261.4 running against Vsphere Vcenter 5.5 using Vsphere ESXI 5.5 on the hypervisor hosts. The Vcenter has different clusters, but we are defining only 3 in the CPI configuration in order to deploy vms to them (in order to have 3 AZs, a cluster maps to an AZ). These clusters have Vsphere HA and DRS  both disabled and they **use local storage (SSDs)**, so when a vm is deployed, the cpi selects a random datastore based on the `datastore_pattern` and continues with the rest of operations to create a VM. Each ESXI server has a local datastore named similar to its name, so the ESXI server `cf-dogo-esxi-01` has a local datastore called `local-ssd-dogo-01`.

This is the CPI config for bosh-init:
```
    vcenter:
      address: X.X.X.X
      user: user
      password: pass
      datacenters:
      - name: XXXXX
        vm_folder: CF_Test/Bosh_VMs
        template_folder: CF_Test/Bosh_Templates
        datastore_pattern: local-ssd*
        persistent_datastore_pattern: data_cf_gold_*
        disk_path: bosh_test_disks
        clusters:
          - CF_rone: {}
          - CF_dogo: {}
          - Online_Prod: {}
```

The main issue we have is when a esxi server is in maintenance mode (or disconnected). The CPI still sees the esxi hypervisor and tries to deploy vms there, and ofc, it fails. It seems it does not pay attention to the status of the server (maintenance status and/or disconnected).

The workaround we found is define a list of datastores by specifing a datastore pattern like `(local-ssd-rone-[0-9]{2})|(local-ssd-dogo-[0-9]{1}[0-2,4-9]{1})`  (in this case we want to avoid using the server/datastore `local-ssd-dogo-03`), but we do not want to do in this way because it needs to re-deploy bosh with bosh-init again (or do some hacks in the bosh director vm and cpi json config).

Is there a way to filter the ESXI servers which are in maintenance mode (or disconnected)?

Thanks!
