### ISSUE TITLE
Upgrade hardware version really working?

### ISSUE THREAD

**Issue by marcohelmerich** [cloudfoundry-incubator/bosh-vsphere-cpi-release#99]
Hi,
we are just trying to get into cloud foundry on vsphere. As the stemcell version 9 is prehistoric and has a lot of issues we would like to bump it to 13. What we are trying ist to put upgrade_hw_version: true in the vm types section.
```
vm_types:
- name: default
  cloud_properties:
    cpu: 2
    upgrade_hw_version: true
    ram: 1024
    disk: 3240
```

wrong place?
